# Generated by Django 4.2.23 on 2025-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ballot_table_alter_choice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
