# Generated by Django 4.2.23 on 2025-07-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ballot_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ballot',
            table='ballots',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choices',
        ),
    ]
