# Generated by Django 4.2.23 on 2025-07-08 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ballot_table_alter_choice_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='core.ballot')),
            ],
            options={
                'db_table': 'voters',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.ballot')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.choice')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.voter')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
