# Generated by Django 4.2.23 on 2025-07-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_voter_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ballot',
        ),
    ]
